Pull request for E2E DETS
eclipse-tractusx/data-exchange-test-service pull request #3
Opened 2023-04-11 11:50 UTC by amoldashwant

This pull request includes  working End-to-end data exchange test service initial source code.

2023-04-11 12:42 UTC, sachinargade123 commented on src/main/java/org/connector/e2etestservice/Utils.java
> +package org.connector.e2etestservice;
Please add copy right header

2023-04-11 12:48 UTC, sachinargade123 commented on CHANGELOG.md
> + - Fetch preconfgiured connector url from properties file
@amoldashwant correct typos

2023-04-11 12:49 UTC, sachinargade123 commented on CHANGELOG.md
> + - Testconnector api changes for autosetup email support
@amoldashwant correct typo

2023-04-11 12:51 UTC, sachinargade123 requested changes
@amoldashwant Please correct typo, add missing copyright header

2023-04-12 05:28 UTC, amoldashwant commented on src/main/java/org/connector/e2etestservice/Utils.java
> +package org.connector.e2etestservice;
Changes done

2023-04-12 05:28 UTC, amoldashwant commented on CHANGELOG.md
> + - Fetch preconfgiured connector url from properties file
Changes done

2023-04-12 05:28 UTC, amoldashwant commented on CHANGELOG.md
> + - Testconnector api changes for autosetup email support
Changes done

2023-04-14 09:37 UTC, Siegfriedk commented
Will merge it and will open an initial contribution for it.

2023-04-14 09:37 UTC, merged