[Feat|DETS] : Preconfigured connector URL fixes and unit tests
eclipse-tractusx/data-exchange-test-service pull request #39
Opened 2024-01-05 05:49 UTC by amoldashwant

## Description

### Fixed
- Preconfigured connector URL '/' issue
- Dynamic asset name generation issue

### Added
- Unit tests for Controller and service

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-01-05 06:30 UTC, sachinargade123 commented on src/main/resources/edc-request-template/sample-asset.json
> +			"type": "data.core.sample"
Use 'type' dynamically from properties file like name attribute.

2024-01-05 08:37 UTC, amoldashwant commented on src/main/resources/edc-request-template/sample-asset.json
> +			"type": "data.core.sample"
Code changes are done. PR updated

2024-01-09 10:15 UTC, sachinargade123 approved these changes
LGTM

2024-01-15 09:00 UTC, almadigabor requested changes
You need to adjust the license headers in the files you modified in this PR to include 2024 like [here](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02#copyright-and-license-header) as well.

2024-01-15 12:23 UTC, amoldashwant commented
@almadigabor '2024' change added in the header

2024-01-18 08:45 UTC, almadigabor approved these changes
LGTM

2024-01-18 08:45 UTC, merged