[Fix|DETS] Fixed veracode security issue CVE-2023-6481
eclipse-tractusx/data-exchange-test-service pull request #40
Opened 2024-02-09 08:55 UTC by amoldashwant

## Description

### Fixed

- Logback vulnerabilities issues for CVE-2023-6481

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-02-09 09:05 UTC, adkumar1 approved these changes
Looks good

2024-02-09 09:35 UTC, sachinargade123 requested changes
Add 2024 copyright for pom.xml file

2024-02-09 10:58 UTC, amoldashwant commented
> Add 2024 copyright for pom.xml file

Copyright updated with this change

2024-02-10 03:15 UTC, sachinargade123 approved these changes
Lgtm

2024-02-12 09:12 UTC, almadigabor approved these changes

2024-02-12 09:12 UTC, merged