docs: Updated legal noticeLegals
eclipse-tractusx/data-exchange-test-service pull request #85
Opened 2024-06-10 11:22 UTC by adkumar1

- This PR contains the changes w.r.t TRG 7.07, TRG7.08

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-11 05:45 UTC, adityagajbhiye9 requested changes

2024-06-11 05:45 UTC, adityagajbhiye9 commented on CONTRIBUTING.md
please check and correct as per TRG 7.0  guidelines.
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01
https://github.com/eclipse-tractusx/sig-infra/blob/main/CONTRIBUTING.md
https://github.com/eclipse-tractusx/sig-infra/pull/476/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055

2024-06-11 05:46 UTC, adityagajbhiye9 commented on CONTRIBUTING.md
and also tick pre-review checks.

2024-06-12 05:16 UTC, adityagajbhiye9 approved these changes
LGTM

2024-06-14 09:19 UTC, tomaszbarwicki approved these changes

2024-06-14 09:19 UTC, merged